version: '3.8'

services:
  # PHP 服務
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: choosemeal_app_${APP_PORT:-8000}
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - choosemeal_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Nginx 服務
  nginx:
    image: nginx:alpine
    container_name: choosemeal_nginx_${APP_PORT:-8000}
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - choosemeal_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # MySQL 服務
  db:
    image: mysql:8.0
    container_name: choosemeal_db_${APP_PORT:-8000}
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${DB_PORT:-3307}:3306"
    networks:
      - choosemeal_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Redis 服務
  redis:
    image: redis:alpine
    container_name: choosemeal_redis_${APP_PORT:-8000}
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6380}:6379"
    networks:
      - choosemeal_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  choosemeal_network:
    driver: bridge

volumes:
  mysql_data:
